# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  projects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'API'

stages:
  - stage: BuildTest
    displayName: "Build and test"
    jobs:
    - job:
      steps:
      - task: NuGetToolInstaller@1

      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: build
          projects: $(projects)
          publishWebProjects: false
          arguments: --configuration $(buildConfiguration) 

      - task: DotNetCoreCLI@2
        displayName: "Unit Tests"
        inputs:
          command: 'test'
          projects: '**/*.UnitTests.csproj'

  - stage: Publish
    displayName: "Publish release"
    dependsOn: BuildTest
    jobs:
    - job:
      steps:
      - task: DotNetCoreCLI@2
        displayName: "Publish"
        inputs:
          command: 'publish'
          publishWebProjects: true
          projects: $(projects)
          arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: '${{ variables.artifactName }}'
          publishLocation: 'Container'

  - stage: DeployDev
    displayName: "Deploy to Dev"
    dependsOn: Publish
    condition: succeeded()
    variables:
      - group: "kv-development"
      - group: "development"
    jobs:
    - job:
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: '${{ variables.artifactName }}'
          targetPath: '$(Build.ArtifactStagingDirectory)'
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'AzureSubscription (949d7eee-adc3-4aaa-bedf-54d3174d11ec)'
          appType: 'webAppLinux'
          WebAppName: 'PortStanleyRun-Api-Dev'
          deployToSlotOrASE: true
          ResourceGroupName: 'rg-dev'
          SlotName: 'production'
          packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
          RuntimeStack: 'DOTNETCORE|6.0'
      - task: FileTransform@1
        inputs:
          folderPath: '$(System.DefaultWorkingDirectory)/**/PortStanleyRun.Api.IntegrationTests'
          fileType: 'json'
          targetFiles: '**/appsettings.test.json'
      - task: DotNetCoreCLI@2
        displayName: "Integration Tests"
        inputs:
          command: 'test'
          projects: '**/*.IntegrationTests.csproj'

  - stage: DeployProd
    displayName: "Deploy to Prod"
    dependsOn: DeployDev
    jobs:
    - job: ManualValidation
      displayName: "Manual Validation"
      pool: server
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: 'mike.horlick@gmail.com'
          instructions: 'Deploy to prod request'
    - job:
      displayName: "Deploy"
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: '${{ variables.artifactName }}'
          targetPath: '$(Build.ArtifactStagingDirectory)'
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'AzureSubscription (949d7eee-adc3-4aaa-bedf-54d3174d11ec)'
          appType: 'webAppLinux'
          WebAppName: 'PortStanleyRun-Api'
          deployToSlotOrASE: true
          ResourceGroupName: 'rg-main'
          SlotName: 'production'
          packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
          RuntimeStack: 'DOTNETCORE|6.0'